# Form implementation generated from reading ui file 'WembleyProject.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QPixmap, QFont
from PyQt6.QtCore import Qt, QRect
from PyQt6.QtWidgets import QProgressBar

class Ui_Login(object):
    def setupUi(self, LoginPage):
        LoginPage.setObjectName("LoginPage")
        LoginPage.resize(980, 717)
        LoginPage.setAutoFillBackground(False)
        LoginPage.setStyleSheet("border: none;\n"
                "background: transparent;\n"
                "background-color: #007FFF;\n"
                "opacity: 0.6;")
        LoginPage.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=LoginPage)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(387, 150, 199, 141))
        self.label.setToolTipDuration(-1)
        self.label.setStyleSheet(
                                "background-color: transparent;"
                                "opacity: 0;")
        pixmap1 = QPixmap("H:\Photo\picture2.jpg")
        self.label.setPixmap(pixmap1)
        self.label.setScaledContents(True)
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(350, 180, 271, 80))
        self.label_2.setStyleSheet(" background-color: #ffffff;\n"
                                "border-radius: 30px;")
        self.label_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.txtUsername = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtUsername.setGeometry(QtCore.QRect(350, 300, 271, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(15)
        self.txtUsername.setFont(font)
        self.txtUsername.setStyleSheet("border-radius: 10px;\n"
                                "border: 2px solid white; \n"
                                "background-color: white;\n"
                                "padding-left: 45px;\n"
                                "")
        self.txtUsername.setText("")
        self.txtUsername.setFrame(True)
        self.txtUsername.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.txtUsername.setCursorPosition(0)
        self.txtUsername.setDragEnabled(False)
        self.txtUsername.setReadOnly(False)
        self.txtUsername.setObjectName("txtUsername")
        self.btnLogin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnLogin.setGeometry(QtCore.QRect(350, 460, 271, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(18)
        font.setBold(True)
        self.btnLogin.setFont(font)
        self.btnLogin.setStyleSheet("QPushButton#btnLogin{\n"
                                "background: white;\n"
                                "border-radius: 10px;\n"
                                "color: black;\n"
                                "}\n"
                                "QPushButton#btnLogin:pressed{\n"
                                "    padding-left: 5px;\n"
                                "    padding-top: 5px;\n"
                                "    background-color: transparent;\n"
                                "\n"
                                "}\n"
                                "QPushButton#btnLogin:hover{\n"
                                "    background-color: #dfa41c;\n"
                                "    opacity: 0.4;\n"
                                "}")
        self.btnLogin.setObjectName("btnLogin")
        self.txtPassword = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtPassword.setGeometry(QtCore.QRect(350, 360, 271, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(15)
        self.txtPassword.setFont(font)
        self.txtPassword.setStyleSheet("border-radius: 10px;\n"
"border: 2px solid white; \n"
"color: black;\n"
"background-color: white;\n"
"padding-left: 45px;")
        self.txtPassword.setText("")
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(360, 310, 30, 30))
        self.label_3.setStyleSheet("image: url('H:/APP UNIVERSITY/CODE PYTHON/CVWembley/SourceIcons/icons8-username-30-1.png');\n"
"")
        self.label_3.setText("")
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(360, 370, 30, 30))
        self.label_4.setStyleSheet("image: url('H:/APP UNIVERSITY/CODE PYTHON/CVWembley/SourceIcons/icons8-secure-30.png');")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")

        self.btnShowpassword = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnShowpassword.setGeometry(QtCore.QRect(580, 370, 30, 30))
        self.btnShowpassword.setStyleSheet("\n"
"QPushButton#btnShowpassword{\n"
"image: url('H:/APP UNIVERSITY/CODE PYTHON/CVWembley/SourceIcons/icons8-eye-30.png');\n"
"}\n"
"QPushButton#btnShowpassword:pressed{\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"")
        self.btnShowpassword.setText("")
        self.btnShowpassword.setObjectName("btnShowpassword")
  
        self.progressBar = QProgressBar(self.centralwidget)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(350, 420, 271, 31))
        font3 = QFont()
        font3.setFamilies([u"Roboto"])
        font3.setPointSize(13)
        self.progressBar.setFont(font3)
        self.progressBar.setStyleSheet(u"QProgressBar{\n"
"	border-radius: 1px;\n"
"	color: white;\n"
"	text-align: center;\n"
"}\n"
"QProgressBar:chunk{\n"
"	border-radius: 5px;\n"
"	 background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:1 rgba(51, 217, 9, 255), stop:0 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"   ")
        self.progressBar.setMinimum(0)
        self.progressBar.setValue(25)
        self.progressBar.setTextVisible(True)

        self.label_2.raise_()
        self.label.raise_()
        self.txtUsername.raise_()
        self.btnLogin.raise_()
        self.txtPassword.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.btnShowpassword.raise_()
        LoginPage.setCentralWidget(self.centralwidget)
        self.retranslateUi(LoginPage)
        QtCore.QMetaObject.connectSlotsByName(LoginPage)

        # Khởi tạo thêm biến
        self.statusLogin = QtWidgets.QLabel(parent=self.centralwidget)
        self.statusLogin.setGeometry(QtCore.QRect(405, 420, 180, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        font.setBold(True)
        self.statusLogin.setFont(font) 
        self.statusLogin.setStyleSheet("color: #dfa41c;")

    def retranslateUi(self, InspectationCubeApp):
        _translate = QtCore.QCoreApplication.translate
        InspectationCubeApp.setWindowTitle(_translate("InspectationCubeApp", "Login"))
        self.txtUsername.setPlaceholderText(_translate("InspectationCubeApp", "TÊN ĐĂNG NHẬP"))
        self.btnLogin.setText(_translate("InspectationCubeApp", "ĐĂNG NHẬP"))
        self.txtPassword.setPlaceholderText(_translate("InspectationCubeApp", "MẬT KHẨU"))
        InspectationCubeApp.setWindowIcon(QtGui.QIcon("H:\Photo\picture2.jpg"))
        InspectationCubeApp.setWindowFlags(Qt.WindowType.CustomizeWindowHint | Qt.WindowType.WindowMinimizeButtonHint | Qt.WindowType.WindowCloseButtonHint)
        
        


